### ISSUE TITLE
Twilio issue

### ISSUE THREAD

**Issue by robertminer1** [snowplow/huskimo#30]
Hi!  I seem to be getting this error after Huskimo download twilio calls.  Any ideas?  Thanks!

```
Temporary file is /tmp/recordings-0-3-2077626786101685059.tsv.gz
Temporary file is /tmp/incoming_phone_numbers-0-0-1416151658393897892.tsv.gz
Exception in thread "main" java.util.NoSuchElementException: None.get
    at scala.None$.get(Option.scala:313)
    at scala.None$.get(Option.scala:311)
    at com.snowplowanalytics.huskimo.channels.twilio.Twilio$$anonfun$2.apply(Twilio.scala:139)
    at com.snowplowanalytics.huskimo.channels.twilio.Twilio$$anonfun$2.apply(Twilio.scala:137)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at com.snowplowanalytics.huskimo.channels.twilio.Twilio$.fetchAndWritePricing(Twilio.scala:137)
    at com.snowplowanalytics.huskimo.channels.twilio.Twilio$$anonfun$fetch$2.apply(Twilio.scala:234)
    at com.snowplowanalytics.huskimo.channels.twilio.Twilio$$anonfun$fetch$2.apply(Twilio.scala:214)
    at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
    at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
    at com.snowplowanalytics.huskimo.channels.twilio.Twilio$.fetch(Twilio.scala:214)
    at com.snowplowanalytics.huskimo.Huskimo$.fetchAll(HuskimoApp.scala:137)
    at com.snowplowanalytics.huskimo.HuskimoApp$delayedInit$body.apply(HuskimoApp.scala:85)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
    at scala.App$class.main(App.scala:71)
    at com.snowplowanalytics.huskimo.HuskimoApp$.main(HuskimoApp.scala:53)
    at com.snowplowanalytics.huskimo.HuskimoApp.main(HuskimoApp.scala)
```

**Comment by alexanderdean** [comment]
Hi @robertminer1 - ah, I think this is a bug. We wrote this for a specific customer who was using the Twilio phone numbers feature, and the code assumes that if you get back a non-empty list of phone numbers, they will all have the `iso_country` field set to non-empty. Using `.get` on a Scala `None` is very bad practice, in any case.

We are not putting any development resources into Huskimo at this time (for a couple of reasons); as a result I think your options are:
1. Fix the bug yourself
2. Create some dummy resources in Twilio so that the extraction succeeds

Sorry we can't be more help!

**Comment by robertminer1** [comment]
Thanks for pointing me in the right direction, closing this.
